# Generated by Django 3.0.4 on 2020-05-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_code', models.CharField(max_length=64, unique=True, verbose_name='Campus Code')),
                ('campus_name', models.CharField(max_length=200, verbose_name='Campus Name')),
                ('campus_add', models.CharField(max_length=200, verbose_name='Campus Address')),
                ('registered_by', models.CharField(max_length=100, verbose_name='Registered By')),
                ('registered_date', models.DateField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100, verbose_name='Updated By')),
                ('updated_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbl_campus',
            },
        ),
    ]
