# Generated by Django 3.0.4 on 2020-09-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_setting', '0002_auto_20200920_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='registered_by',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='registered_date',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='updated_date',
        ),
    ]
